name: 'Bug report'
about: 'Create a report to help us improve'
title: '[Bug report]'
labels: ''
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        # 感谢您的反馈
          Blog 的 Issue 列表接受 bug 报告或是新功能请求。

        在发布一个 Issue 前，请确保：
        - 在 [常见问题](https://github.com/jiazengp/blog/discussions/2)、[更新日志](https://github.com/jiazengp/blog/blob/main/CHANGELOG.md) 和 [旧Issue列表](https://github.com/jiazengp/blog/issues?q=is%3Aissue) 中搜索过你的问题。（你的问题可能已有人提出，也可能已在最新版本中被修正）
        - 如果你发现一个已经关闭的旧 Issue 在最新版本中仍然存在，不要在旧 Issue 下面留言，请建一个新的 issue。

  - type: input
    id: reproduce
    attributes:
      label: 错误页面的链接
      description: 请提供问题页面的完整链接。请不要填无关链接，否则你的 Issue 将被关闭。
      placeholder: 请填写

  - type: textarea
    id: reproduceSteps
    attributes:
      label: 重现步骤
      description: 请清晰的描述重现该 Issue 的步骤，这能帮助我们快速定位问题。没有清晰重现步骤将不会被修复，标有 'need reproduction' 的 Issue 在 7 天内不提供相关步骤，将被关闭。
      placeholder: 请填写

  - type: textarea
    id: expect
    attributes:
      label: 期望结果
      placeholder: 请填写

  - type: textarea
    id: actual
    attributes:
      label: 实际结果
      placeholder: 请填写

  - type: input
    id: browsersVersion
    attributes:
      label: 浏览器版本
      placeholder: Chrome(8.213.231.123)

  - type: input
    id: systemVersion
    attributes:
      label: 系统版本
      placeholder: MacOS(11.2.3)

  - type: textarea
    id: environmentInfo
    attributes:
      label: 环境信息
      description: 输出 `envinfo`
      placeholder: 请在此处粘贴 `envinfo` 的输出

  - type: textarea
    id: remarks
    attributes:
      label: 补充说明
      description: 可以是遇到这个问题场景、上下文、错误提示的截图等信息。
      placeholder: 请填写
